# Waypoints
wp1_z: 4.0 # Flight Altitude
wp2_x: 2.0 # Longitude of GPS Box
wp2_y: 3.0 # Latitude of GPS Box
wp3_z: 0.0 # Altitude of ground where GPS box is located
# Parameters Acceleration and Velocity
v_max: 0.8 # Maximum Speed
a_max: 0.7 # Maximum Acceleration
v_scaling_descending: 0.2
v_scaling_ascending: 0.2
v_scaling_recovery_traverse: 0.1
# Release mechanism
height_drop: 0.1 # drop height for release mechanism
steps_dynamixel: 24570 # incremental steps (Height / Screw_Pitch * Resolution = 6 mm / 1 mm * 4095)
# Recovery mechanism
height_overlapping_net: 0.08 # for net [POSITIVE SIGN] 
height_overlapping_magnet: 0.05 # for magnet [POSITIVE SIGN]
# Configuration Parameters
trans_uav_rokubi_x: 0.1
trans_uav_rokubi_y: 0.0
trans_uav_rokubi_z: -0.2