# Waypoints
wp1_z: 4.0 # Flight Altitude
wp2_x: 5.0 # Longitude of GPS Box
wp2_y: 2.0 # Latitude of GPS Box
wp3_z: 0.0 # Altitude of ground where GPS box is located
# Parameters for drone
v_max: 1.0 # Maximum Speed
a_max: 1.0 # Maximum Acceleration